### ISSUE TITLE
Airbrake Message Rejected

### ISSUE THREAD

**Issue by jamesward** [teamon/play-airbrake#1]
My messages to Airbrake are rejected when using this plugin.  Here is the error:

```
Element 'session': Missing child element(s). Expected is ( var ).
```

Here is my test app: https://github.com/teamon/play-airbrake

**Comment by teamon** [comment]
@jamesward Looks like you missed the correct url for your test app ;)

**Comment by jamesward** [comment]
Whoops.  Sorry about that.  The correct URL is: https://github.com/jamesward/play2airbrake

**Comment by teamon** [comment]
This is probably because your `request.session.data` is empty so the message sent to air brake has empty `<session></session>` tag. I must check if `<session>` is required, if not it's trivial fix to not include it in `request.session.data` is empty.

**Comment by jamesward** [comment]
Thanks!  I've tested `0.1.1` and it seems to be working great!
