### ISSUE TITLE
Remove key from cache using standard api causes NPE

### ISSUE THREAD

**Issue by Enalmada** [teamon/play-airbrake#3]
The documentation states that the only way to remove a key from cache is to pass in a null with 0
Cache.set("item.key", null, 0);
https://github.com/playframework/Play20/wiki/JavaCache

I see that serialize throws null if null is passed in, but I think perhaps passing null and 0 should be a special case and internally call this instead:
play.api.Play.current.plugin[MemcachedPlugin].get.api.remove("keyToRemove")

**Comment by teamon** [comment]
How is it related to plan-airbrake?

**Comment by Enalmada** [comment]
oh no i am on the wrong page...im an idiot.  Was looking into how awesome airbrake is on another tab. sorry

**Comment by teamon** [comment]
@Enalmada :)

**Comment by Enalmada** [comment]
Is there any way to "delete" issues?

**Comment by teamon** [comment]
I don't see such option. Closed is good enough.

**Comment by Enalmada** [comment]
BTW
Being on the java side of play I would love to use the plugin but apparently scala has a different requestHeader type.  I tried messing around with it a bit to see if I could hack it from my side but I am not skilled enough to get it to work but if you ever decide to support a java version of play, it might be possible to have another version of notify that takes in the actual components you need rather than the whole requestheader and then the java side can call that version.  Something like this...

```
@Override
public Result onError(RequestHeader request, Throwable t) {
    Airbrake.notify(request.method(), request.uri(),  Context.current().session().entrySet(), t);
    return super.onError(request, t);
}
```

**Comment by teamon** [comment]
@Enalmada Could you make a separate issue "Java support" with this comment?

**Comment by Enalmada** [comment]
oh would love to sure.  Didn't want to create more shame for myself if you wern't interested..

**Comment by teamon** [comment]
If that can make someone happy I am interested :)
